site_name: "Jersh's Useful Scripts"
site_url: https://scripts.rossjm.dev/
nav:
  - Home: index.md
  - Shell: shell.md
  - Proxmox: proxmox.md
  


theme:
    # favicon: images/favicon-32x32.png
    # logo: images/apple-touch-icon.png
    name: material
    features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.side
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    language: en
    palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - social
  - search

extra:
   social:
     - icon: fontawesome/brands/github-alt
       link: https://github.com/coloredbytes/scripts

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde




copyright: |
  &copy; 2024 <a href="https://github.com/coloredbytes"  target="_blank" rel="noopener">Joshua Ross</a>