name: Auto Approve Renovate Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:  # Allows manual triggering for open PRs

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Get open pull requests from renovate[bot]
        id: pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pulls = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const renovatePRs = pulls.data.filter(pr => pr.user.login === 'renovate[bot]');
            return renovatePRs.map(pr => pr.number);

      - name: Approve PRs
        if: steps.pr.outputs.length > 0
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        for_each: pr_number in steps.pr.outputs
